version: '3.8'

volumes:
  pg_data:

services:
  redis:
    image: redis:7.0.5-alpine
    ports:
      - "6379:6379"

  db:
    image: postgres:latest
    environment:
      - POSTGRES_PASSWORD=qwery
    ports:
      - "5444:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data

  app:
    build: /app
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - ./app:/app
    ports:
      - "8000:8000"