version: '3.8'

volumes:
  pg_data:

services:
  redis:
    image: redis:7.0.5-alpine
    container_name: tema-tokens-redis
    restart: always
    expose:
      - 6379
    ports:
      - "6379:6379"
    command: "redis-server --requirepass laksjdweriuywyueryuuwey123123 --user tokens"

  db:
    restart: always
    image: postgres:latest
    environment:
      - POSTGRES_PASSWORD=qwery
    ports:
      - "5444:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
    expose:
      - 5432

  antidoubles_app:
    restart: always
    build: ./antidoubles_app
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - ./antidoubles_app:/antidoubles_app
    expose:
      - 8000
    env_file:
      - ./antidoubles_app/.env

  auth_app:
    restart: always
    build: ./auth_app
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - ./auth_app:/auth_app
    env_file:
      - ./auth_app/.env
    expose:
      - 8000

  nginx:
    restart: always
    image: nginx:1.19.8-alpine
    ports:
      - "88:80"
    volumes:
      - ./nginx:/etc/nginx/conf.d