version: '3.8'

volumes:
  pg_data:

services:
  redis:
    restart: always
    image: redis:7.0.5-alpine
    expose:
      - 6379

  db:
    restart: always
    image: postgres:latest
    environment:
      - POSTGRES_PASSWORD=qwery
    ports:
      - "5444:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
    expose:
      - 5432

  app:
    restart: always
    build: ./app
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - ./app:/app
    expose:
      - 8000

  nginx:
    image: nginx:1.19.8-alpine
    ports:
      - "88:80"
    volumes:
      - ./nginx:/etc/nginx/conf.d