"""project subdomain uniq remove

Revision ID: af67ac06d7f7
Revises: 2f7323b73a2b
Create Date: 2024-12-05 09:57:47.707396

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'af67ac06d7f7'
down_revision: Union[str, None] = '2f7323b73a2b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('projects_subdomain_key', 'projects', type_='unique')
    op.add_column('widgets', sa.Column('name', sa.String(), nullable=True))
    op.create_unique_constraint(None, 'widgets', ['name'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'widgets', type_='unique')
    op.drop_column('widgets', 'name')
    op.create_unique_constraint('projects_subdomain_key', 'projects', ['subdomain'])
    # ### end Alembic commands ###
