name: CI/CD Pipeline
on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2

      - name: Deploy to server via SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          password: ${{ secrets.SERVER_PASSWORD }}
          script: |
            cd /root/amo-anti-doubles
            
            # Получение хеша последнего рабочего коммита
            last_commit=$(git rev-parse HEAD)
            
            # Обновление кода
            git pull origin master
            
            docker compose down
            docker compose pull
            docker compose up -d --build
            sleep 10
            
            if [ $(curl -s -o /dev/null -w "%{http_code}" http://localhost:88/auth/) -eq 404 ]; then
              echo "Контейнер auth работает отлично"
            else
              echo "Auth error:"
              docker logs amo-anti-doubles-auth_app-1
              echo "Отмена изменений"
              
              git reset --hard $last_commit
              
              docker compose down
              docker compose pull
              docker compose up -d --build
              exit 1
            fi

            if [ $(curl -s -o /dev/null -w "%{http_code}" http://localhost:88/antidoubles/) -eq 404 ]; then
              echo "Контейнер antidoubles работает отлично"
            else
              echo "Auth error:"
              docker logs amo-anti-doubles-antidoubles-app-1
              echo "Отмена изменений"
              
              git reset --hard $last_commit
              
              docker compose down
              docker compose pull
              docker compose up -d --build
              exit 1
            fi
